version: "3"

services:
  app:
    restart: always
    build: .
    ports:
      - "3000"
    depends_on:
      - mongo
      - redis-server

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

  redis-server:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
